github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/utilities-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/watchexec"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Watchexec CLI
  id:              watchexec
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       watchexec-.+-x86_64-unknown-linux-musl.tar.xz
    owner:      watchexec
    repository: watchexec
    tag_filter: v(2.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

# ARM64
- name:            Watchexec CLI ARM64
  id:              watchexec
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       watchexec-.+-aarch64-unknown-linux-musl.tar.xz
    owner:      watchexec
    repository: watchexec
    tag_filter: v(2.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:    arm64
