api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Watchexec binary tool"
  homepage = "https://github.com/paketo-buildpacks/watchexec"
  id = "paketo-buildpacks/watchexec"
  keywords = ["watchexec", "reloadable", "processes"]
  name = "Paketo Buildpack for Watchexec"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/watchexec/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:a2c01f82fb4cdafca1fa12cb88e4a1145dec63364dbdf92664efbaac3bb44dd2"
    cpe = "cpe:2.3:a:watchexec:watchexec:2.7.2:*:*:*:*:*:*:*"
    id = "watchexec"
    name = "Watchexec"
    os = "linux"
    purl = "pkg:generic/watchexec@2.7.2?checksum=a2c01f82fb4cdafca1fa12cb88e4a1145dec63364dbdf92664efbaac3bb44dd2&download_url=https://github.com/watchexec/watchexec/releases/download/v2.7.2/watchexec-2.7.2-x86_64-unknown-linux-musl.tar.xz"
    source = "https://github.com/watchexec/watchexec/archive/refs/tags/v2.7.2.tar.gz"
    source-checksum = "sha256:ad87aac074e5d1b018bb50ef98240911cd31d96d68d9b8ac0f02c14879930f50"
    stacks = ["*"]
    uri = "https://github.com/watchexec/watchexec/releases/download/v2.7.2/watchexec-2.7.2-x86_64-unknown-linux-musl.tar.xz"
    version = "2.7.2"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:83cbce2ffc85adaab14d6ded09b292f4383358ac6d9a51b4e4e083df0cb7c831"
    cpe = "cpe:2.3:a:watchexec:watchexec:2.7.2:*:*:*:*:*:*:*"
    id = "watchexec"
    name = "Watchexec"
    os = "linux"
    purl = "pkg:generic/watchexec@2.7.2?checksum=83cbce2ffc85adaab14d6ded09b292f4383358ac6d9a51b4e4e083df0cb7c831&download_url=https://github.com/watchexec/watchexec/releases/download/v2.7.2/watchexec-2.7.2-aarch64-unknown-linux-musl.tar.xz"
    source = "https://github.com/watchexec/watchexec/archive/refs/tags/v2.7.2.tar.gz"
    source-checksum = "sha256:ad87aac074e5d1b018bb50ef98240911cd31d96d68d9b8ac0f02c14879930f50"
    stacks = ["*"]
    uri = "https://github.com/watchexec/watchexec/releases/download/v2.7.2/watchexec-2.7.2-aarch64-unknown-linux-musl.tar.xz"
    version = "2.7.2"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:b5bcd00ae3ebb53f7ea5d499fdf98bda14711589a7ecc0619e1847586beaa24d"
    cpe = "cpe:2.3:a:watchexec:watchexec:2.7.3:*:*:*:*:*:*:*"
    id = "watchexec"
    name = "Watchexec"
    os = "linux"
    purl = "pkg:generic/watchexec@2.7.3?checksum=b5bcd00ae3ebb53f7ea5d499fdf98bda14711589a7ecc0619e1847586beaa24d&download_url=https://github.com/watchexec/watchexec/releases/download/v2.7.3/watchexec-2.7.3-x86_64-unknown-linux-musl.tar.xz"
    source = "https://github.com/watchexec/watchexec/archive/refs/tags/v2.7.3.tar.gz"
    source-checksum = "sha256:6f395178a963ffd478f0ee2e13146d375e8bbe4fec6859a56a0086a90e07e6f2"
    stacks = ["*"]
    uri = "https://github.com/watchexec/watchexec/releases/download/v2.7.3/watchexec-2.7.3-x86_64-unknown-linux-musl.tar.xz"
    version = "2.7.3"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:80bd9acfc25e4035624d99585b2f920add5ecbdc0c732c4e42fa1451b63d80a5"
    cpe = "cpe:2.3:a:watchexec:watchexec:2.7.3:*:*:*:*:*:*:*"
    id = "watchexec"
    name = "Watchexec"
    os = "linux"
    purl = "pkg:generic/watchexec@2.7.3?checksum=80bd9acfc25e4035624d99585b2f920add5ecbdc0c732c4e42fa1451b63d80a5&download_url=https://github.com/watchexec/watchexec/releases/download/v2.7.3/watchexec-2.7.3-aarch64-unknown-linux-musl.tar.xz"
    source = "https://github.com/watchexec/watchexec/archive/refs/tags/v2.7.3.tar.gz"
    source-checksum = "sha256:6f395178a963ffd478f0ee2e13146d375e8bbe4fec6859a56a0086a90e07e6f2"
    stacks = ["*"]
    uri = "https://github.com/watchexec/watchexec/releases/download/v2.7.3/watchexec-2.7.3-aarch64-unknown-linux-musl.tar.xz"
    version = "2.7.3"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/watchexec/watchexec/blob/main/LICENSE"

  [[metadata.dependency-constraints]]
    constraint = "2.*"
    id = "watchexec"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
